version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: music_library
      MYSQL_USER: ml_user
      MYSQL_PASSWORD: ml_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ml_user
      DB_PASS: ml_pass
      DB_NAME: music_library
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data:
